[package]
name = "oxidar-ls"
version = "0.1.0"
authors = ["Hernan G. Gonzalez <contact@hernan.rs>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
bytes = "1.3"
thiserror = "1.0"

[lints.rust]
unsafe_code = "forbid"
