name: Pull Request

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check changes.
      uses: danieljimeneznz/ensure-files-changed@v4.1.0
      with:
        require-changes-to:
        prevent-changes-to: |
          *.toml
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Format
      run: cargo fmt --verbose
    - name: Lint
      run: cargo clippy --verbose
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Congratulations
      uses: actions/github-script@v7
      with:
        script: |
          // Get a list of all issues created by the PR opener
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Felicitaciones! Completaste el nivel 💪🏼`
          })
