name: Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Ensure Files Changed
      uses: danieljimeneznz/ensure-files-changed@v4.1.0
      with:
        require-changes-to:
        prevent-changes-to: |
          *.toml
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Format
      run: cargo fmt --verbose
    - name: Lint
      run: cargo clippy --verbose
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
